version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: DomiruthPostgres
    ports:
      - '5432:5432' 
    environment:
      POSTGRES_DB: domiruth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: